### ISSUE TITLE
webweb.html writes to site-packages by default

### ISSUE THREAD

**Issue by jg-you** [dblarremore/webweb#29]
`html_file` is set to the base location of the package.
Which ends up a protected site-package location when one installs the package via setup.py or pipy. 
This cause problems on systems that have tight permission control. 
You either have to sudo the python instance to let it write to the protected location or to patch the package so that it writes elsewhere.

Option 1 has the additional downside that uninstalling the package leaves the html file behind.
This means a phantom webweb package that will import but be empty.

I'd suggest having the package write to /tmp/ by default or to have the options at least exposed instead of hidden as a `@property`

**Comment by hneutr** [comment]
ah! thank you for pointing this out — I'm fixing it as we speak. 

The solution (I think) is to distribute a generic `webweb.html` file with the dist, and only write to another file when calling `save`

---

on second thought, I'm not sure this will help things — it'll still be trying to save to a write-protected location.

---

on third thought, here's the solution I'll be going with:

https://stackoverflow.com/questions/847850/cross-platform-way-of-getting-temp-directory-in-python

**Comment by dblarremore** [comment]
Flagging/scoping for future github archaeology: MATLAB version just writes to whatever your current MATLAB directory is, so this is a python-only issue. Third option suggested above (getting temp directory) seems wise!

**Comment by hneutr** [comment]
Hey @jg-you! I've pushed up the change that I believe will fix this and updated the pip distribution, but want to make sure the issue is resolved before closing this out — if you happen to test it out, let me know if it resolves the issue!

**Comment by jg-you** [comment]
@hneutr Works like a charm!
