### ISSUE TITLE
new features to consider for future releases

### ISSUE THREAD

**Issue by angelosalatino** [dblarremore/webweb#35]
Hi,
I had the chance to put my hands over **Webweb** to create some visualizations. In my opinion, this is a valuable resource, and I like it a lot for two main reasons: (i) it works in Python and (ii) it is dynamic (I can move nodes around). However, when I had to create sophisticated visualizations, I stumbled as I didn't know how to implement certain things.
Here I am listing a couple of features that are really worth considering for next releases:
- edge style: solid, dashed, dotted, dashdot
- arrowheads: this is useful for directed graphs and mixed graphs (directed and undirected)
- define our own color palette (instead of predefined)
- zoom in/zoom out over the network
- change node shape: squared, picture, icon

If I have further ideas I will let you know.

Nevertheless, amazing job. Thank you.
Angelo

**Comment by hneutr** [comment]
Hey Angelo! These are great ideas — thank you for taking the time to put them to record. 

I've created an issue for the color palette, and there's an issue already for the zoom — I agree these would really improve the package.

The cosmetic features — edge style, arrowheads, changing node display — I agree would be really sweet to have, but at the moment, there are a couple other issues that are higher priority and I want to be transparent: I'm not sure they're going to get to the burner. 

If you'd like to incorporate them into a particular visualization, though, there are a couple options: one would be downloading the SVG and altering that file yourself to suit your liking; another would be jumping into the rat's nest and forking.

Again, I really appreciate the thought you've put into this. Bringing up the custom colorschemes got me noodling, and I'd love to hear if you have comments on how I'm imagining implementing that feature — the issue for that is [here](https://github.com/dblarremore/webweb/issues/36). 

I'm going to close this issue in favor the specific issues!

- hne
