### ISSUE TITLE
TypeError: Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by jg-you** [dblarremore/webweb#38]
I create a networkx graph where the nodes are np.int64.

This causes a JSON error when trying to visualize the edge list; one needs to recast the node ID to integers to avoid errors, which is not necessarily easy to diagnosis.

Don't know if this can be avoided easily?

Here's the traceback:

    /usr/lib/python3.7/site-packages/webweb/webweb.py in show(self)
         64         """
         65         with open(self.html_file, 'w') as f:
    ---> 66             f.write(self.html)
         67 
         68         webbrowser.open_new("file://" + self.html_file)

    /usr/lib/python3.7/site-packages/webweb/webweb.py in html(self)
        113             blobjs=self.get_client_content('js', 'Blob.js'),
        114             filesaverjs=self.get_client_content('js', 'FileSaver.min.js'),
    --> 115             json=self.json,
        116             webwebjs=self.get_client_content('js', 'webweb.v5.js'),
        117         )

    /usr/lib/python3.7/site-packages/webweb/webweb.py in json(self, title)
         86             "display" : vars(self.display),
         87             'networks' : { name : vars(data) for name, data in vars(self.networks).items()},
    ---> 88             "title" : self.title,
         89         })
         90 

    /usr/lib/python3.7/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
        229         cls is None and indent is None and separators is None and
        230         default is None and not sort_keys and not kw):
    --> 231         return _default_encoder.encode(obj)
        232     if cls is None:
        233         cls = JSONEncoder

    /usr/lib/python3.7/json/encoder.py in encode(self, o)
        197         # exceptions aren't as detailed.  The list call should be roughly
        198         # equivalent to the PySequence_Fast that ''.join() would do.
    --> 199         chunks = self.iterencode(o, _one_shot=True)
        200         if not isinstance(chunks, (list, tuple)):
        201             chunks = list(chunks)

    /usr/lib/python3.7/json/encoder.py in iterencode(self, o, _one_shot)
        255                 self.key_separator, self.item_separator, self.sort_keys,
        256                 self.skipkeys, _one_shot)
    --> 257         return _iterencode(o, 0)
        258 
        259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

    /usr/lib/python3.7/json/encoder.py in default(self, o)
        177 
        178         """
    --> 179         raise TypeError(f'Object of type {o.__class__.__name__} '
        180                         f'is not JSON serializable')
        181

**Comment by hneutr** [comment]
Yo! Thanks for the issue 👍 — this seems like something to be handled on webweb's end (we already do so for numpy's ndarrays. I'm hoping to have a fix up today or tomorrow!

**Comment by hneutr** [comment]
Hey JG! I've patched the fix (wrapping the call to `json.dumps` in a function that tries to convert numpy types to python types), so am going to close the issue.

If for some reason you do still see it popping up, do let me know and if possible (and it's shareable!) send a snippet of code you can generate it with. 

Anyways, thanks again for taking the time to make an issue!
