### ISSUE TITLE
Switch to pathlib broke webweb show() on linux

### ISSUE THREAD

**Issue by jg-you** [dblarremore/webweb#44]
I'm currently testing the latest version of webweb (0.0.35) for the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1458).

Here's the new output of the minimal code:

    In [1]: import webweb                                                                                                               

    In [2]: from webweb import Web 
       ...:  
       ...: # make a list of unweighted edges 
       ...: edge_list = [[1, 2], [2, 3], [3, 4]] 
       ...:  
       ...: # instantiate webweb and show the result 
       ...: Web(edge_list).show()                                                                                                       

    In [3]: gio: file://tmp/webweb.html: Error when getting information for file “/webweb.html”: No such file or directory  

I'm running archlinux, python 3.7.3, webweb 0.0.35

**Comment by jg-you** [comment]
As far as *Linux* is concerned, removing "file:/"  [from line 90 of webweb.py](https://github.com/dblarremore/webweb/blob/master/webweb/webweb.py#L90) should fix the bug.
Don't know how this affects Windows / Mac?

**Comment by hneutr** [comment]
I appreciate you pointing this out, and for the triage — the information is really helpful. 

I tested the change and, on osx at least, the removal causes the file to not be opened. I am looking into how to resolve this. I’ll post again when I’ve got a working solution!

**Comment by hneutr** [comment]
@jg-you, after a bit of exploring, it seems (to me) there are only two places that could be causing this:
- switching `file://` --> `file:/`
- using `path.resolve()`, though I'm not sure why that would. 

I'm proposing changing the line to the following:
`webbrowser.open_new("file://" + str(path))`
which I've confirmed works on mac, and believe addresses both possible issues, though I haven't been able to test it on a linux environment. 

Would you be willing to try subbing that line in, and seeing if that works?

**Comment by jg-you** [comment]
Works like a charm :+1:

**Comment by hneutr** [comment]
@jg-you — made the change in `0.0.36`!
