### ISSUE TITLE
How to increase node's name font size?

### ISSUE THREAD

**Issue by lgg** [dblarremore/webweb#54]
How i can increase the size of node's name?

**Comment by hneutr** [comment]
Hi @igg! Right now there's not an easy way to do this. If you're looking for how to do so in a static image (i.e., if you're using the visualization as a figure), you could save it as an SVG and alter the fontsize of the text elements yourself. Not ideal, I know...

I am, however, working on a big overhaul, and this is something that would be easy to throw in as a setting.

Right now, there's a single text size: 12pt font. However, there are multiple "text" elements:
- node names
- legend titles
- legend content
- possibly later: edge weights

My plan will be to define the following settings, which will take positive integer values and be converted into browser `pt` equivalent:
- `defaultFontSize`; default `12`
- `nodeNameFontSize`; default undefined
- `legendTitleFontSize`; default undefined
- `legendContentFontSize`; default undefined
- `edgeWeightFontSize`; default undefined

If any of `nodeNameFontSize`, `legendTitleFontSize`, `legendContentFontSize`, or `edgeWeightFontSize` is undefined, then `defaultFontSize` will apply.

If you have any feedback, I'd be more than interested!

**Comment by lgg** [comment]
@hneutr Thank you very much for replay. I will wait for the update that you said. It looks useful and awesome!
